apiVersion: v1
kind: Secret
metadata:
  name: hct-alquiler-secret
  namespace: hct-alquiler-vehiculos
type: Opaque
stringData:
  DB_URL: "r2dbc:postgresql://ep-old-union-at7ovm0b-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslMode=require"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "TU_PASSWORD"

