apiVersion: v1
kind: Service
metadata:
  name: hct-alquiler-service
  namespace: hct-alquiler-vehiculos
spec:
  type: ClusterIP
  selector:
    app: hct-alquiler
  ports:
    - port: 8083
      targetPort: 8083
