apiVersion: v1
kind: Service
metadata:
  name: hct-frontend-service
  namespace: hct-alquiler-vehiculos
spec:
  type: NodePort
  selector:
    app: hct-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

